// c1_nlp_product_captionApp.swift
// c1_nlp_product_caption
//
// App entry point — generated by Xcode, no changes needed.

import SwiftUI

@main
struct c1_nlp_product_captionApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
